export const UAM_CONSTANTS = {
EMAIL :'email',
REQUIRED :'required',
TRUE :true,
FALSE :false,
ACTIVE :'Active'
}
export const UAM_LABELS = { 
    USER_CRUD_FIRSTNAME_LABEL:"First Name",
    USER_CRUD_LASTTNAME_LABEL:"Last Name",
    USER_CRUD_EMAIL_LABEL:"Email Address",
    USER_CRUD_USERNAME_LABEL:"Username",
    USER_CRUD_USERGROUP_LABEL:"Inventory Role",
    USER_CRUD_ADD_SUCCESS :"{0} has been added.",
    USER_CRUD_FIELD_VALIDATION : "{0} is required",
    USER_CRUD_FIELD_EMAIL_VALIDATION :"Please enter a valid email.",
    USER_CRUD_ADD_FAILED :"Add User Failed",
    USER_CRUD_ADD_FAILED_UNKNOWN :"Unable to add user {0}.",
    USER_CRUD_PASSWORD_RESET:"RESET TEMPORARY PASSWORD",
    USER_CRUD_ACCOUNT_STATUS:"Account Status",
    USER_CRUD_RESET_SUCCESS:"Password reset link emailed to user {0}.",
    USER_CRUD_LOCK_SUCCESS:"User {0} locked.",
    USER_CRUD_UNLOCK_SUCCESS:"User {0} unlocked.",
    USER_CRUD_LOCK_FAILED:"Unable to lock user {0}.",
    USER_CRUD_UNLOCK_FAILED:"Unable to unlock user {0}.",
    USER_CRUD_STATUS_FAILED :"Status Change Failed",
    USER_CRUD_UPDATE_FAILED :"Edit User Failed",
    USER_CRUD_RESET_MAIL_FAILED:"Unable to send password reset email to user {0}.",
    USER_CRUD_RESET_FAILED :"Reset Password Failed",
    USER_CRUD_EDIT_SUCCESS :"{0} has been updated.",
    USER_CRUD_EDIT_FAILED_UNKNOWN :"Unable to update user {0}.",
    USER_CRUD_DELETE_FAILED_HEADER:"Delete {0} Failed",
    USER_CRUD_DELETE_FAILED_UNKNOWN:"Unable to delete user {0}.",
    USER_CRUD_DELETE_SUCCESS: "{0} has been deleted.",
    USER:"User",
    USER_CRUD_DELETE_FAILED_DEFAULT_USER:"Default admin user cannot be deleted.",
    USER_CRUD_DELETE_FAILED_LOGGED_USER:"You cannot delete yourself while you are logged in.",
    CONFIRM_DELETE_HEADER:"Confirm Delete",
    CONFIRM_DELETE_MESSAGE:"Are you sure you want to delete",
    TENANT_CRUD_LOCK_SUCCESS:"Tenant {0} deactivated.",
    TENANT_CRUD_UNLOCK_SUCCESS:"Teanant {0} activated.",
    TENANT_CRUD_LOCK_FAILED:"Unable to activate tenant {0}.",
    TENANT_CRUD_UNLOCK_FAILED:"Unable to deactivate tenant {0}.",
    TENANT_CRUD_STATUS_FAILED :"Status Change Failed",
    TENANT_CRUD_DELETE_FAILED_UNKNOWN:"Unable to delete tenant {0}.",
    TENANT_HEADER:"Tenant",
    DELETE:"DELETE",
    SAVE: "Save",
    CANCEL: "Cancel",
    ACTIVE : "ACTIVE",
    LOCKED : "LOCKED",
    TENANT_NAME:'Tenant Name',
    CITY:'City',
    COUNTRY:'Country',
    ADDRESS:'Address',
    PROFILE:'Profile',
    CONTACT_NAME:'Contact Name',
    EMAIL:'Email Address',
    FROM_EMAIL:'From',
    FROM_DISPLAY_NAME:'From Display Name',
    REPLY_TO_EMAIL:'Reply To',
    SHARED_PROFILES:"Shared Profiles",
    TENANT_ADMINISTRATOR:"Tenant Administrator",
    EMAIL_SETTINGS:"Email Settings",
    CONTACT_INFO:'Contact Information',
    USERNAME:'Username',
    TENANT_ADD_HEADING:'ADD TENANT',
    TENANT_EDIT_HEADING: 'EDIT TENANT',
    TENANT_CRUD_TENANTPORTALURL : 'Tenant Portal URL',
    TENANT_CRUD_RESETPW : 'RESET TEMPORARY PASSSWORD',
    ADD_USERGROUP_FAILED: "Add Inventory Role Failed",
    USERGROUP_EDIT_HEADING: "Edit Inventory Role",
    UPDATE_USERGROUP_FAILED: "Edit Inventory Role Failed",
    USERGROUP_ADD_HEADING: "Add Inventory Role",
    UPDATED: "has been updated",
    ADDED: "has been added",
    DELETED: "has been deleted",
    INVENTORY_NAME:"Inventory Role Name",
    DESCRIPTION:"Description",
    SHARING_PROFILE_FAILED: "Profile Sharing Failed",
    CATEGORY : "Saved Search Category",
    TEMPLATE_SEARCH:"Template Search",
    QUERY:"Query",
    PROMPT:"Prompt",
    QUERY_RESULTS:'Query Results',
    SEARCH_FAILED:'Search Failed',
    SEARCH: "Search",
    QUERYDESCRIPTION:"Query Description",
    QUERYTYPE:"Query type",
    QUERYNAME:"Query Name",
	ADD_SEARCHPAYLOAD_FAILED:'Create Search Payload Failed',
    UPDATE_SEARCHPAYLOAD_FAILED:'Update Search Payload Failed',
    DELETE_SEARCHPAYLOAD_FAILED:'Delete Search Payload Failed',
    SELECT_QUERY_TO_EDIT:'Select query to edit',
    PLEASE_SELECT_QUERY:'Please Select the Query to be Edited',
    ERROR:"ERROR",
    RECORD_NOT_EXISTS:"Record Does not exists"

}
